export default [
    {
        id: 1,
        homeimg: './image/1x/Asset 1.png',
        awayimg: './image/1x/kia.png',
        date: '2025.06.19',
        location: '수원 18:00',
        homename: 'KT',
        awayname: 'KIA',
        homescore: '0',
        awayscore: '1',
    },
    {
        id: 2,
        homeimg: './image/1x/Asset 1.png',
        awayimg: './image/nc1.png',
        date: '2025.06.18',
        location: '수원 15:00',
        homename: 'KT',
        awayname: 'NC',
        homescore: '3',
        awayscore: '2',
    },
    {
        id: 3,
        homeimg: './image/SSG.png',
        awayimg: './image/1x/Asset 1.png',
        date: '2025.06.17',
        location: '인천 17:00',
        homename: 'SSG',
        awayname: 'KT',
        homescore: '5',
        awayscore: '9',
    },
];
