export default [
    {
        id: 1,
        year: 2025,
        eng: ['1 JAN', '2 FEB', '3 MAR', '4 APR', '5 MAY', '6 JUN', '7 JUL'],
    },
    {
        id: 2,
        year: 2024,
        eng: [
            '1JAN',
            '2FEB',
            '3MAR',
            '4APR',
            '5MAY',
            '6JUN',
            '7JUL',
            '8AUG',
            '9SEP',
            '10OCT',
            '11NOV',
            '12DEC',
        ],
    },
    {
        id: 3,
        year: 2023,
        eng: [
            '1JAN',
            '2FEB',
            '3MAR',
            '4APR',
            '5MAY',
            '6JUN',
            '7JUL',
            '8AUG',
            '9SEP',
            '10OCT',
            '11NOV',
            '12DEC',
        ],
    },
    {
        id: 4,
        year: 2022,
        eng: [
            '1JAN',
            '2FEB',
            '3MAR',
            '4APR',
            '5MAY',
            '6JUN',
            '7JUL',
            '8AUG',
            '9SEP',
            '10OCT',
            '11NOV',
            '12DEC',
        ],
    },
    {
        id: 5,
        year: 2021,

        eng: [
            '1JAN',
            '2FEB',
            '3MAR',
            '4APR',
            '5MAY',
            '6JUN',
            '7JUL',
            '8AUG',
            '9SEP',
            '10OCT',
            '11NOV',
            '12DEC',
        ],
    },
];
